CC = cc
CFLAGS = -Wall -Wextra -Werror
NAME = ft_printf.a
SRC = ft_printf.c  helper_functions.c print_char.c print_string.c print_void.c print_decimal.c print_integer.c print_unsigned_decimal.c print_hexa_lower.c print_hexa_upper.c
OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	ar rcs $(NAME) $(OBJ)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all


